### ISSUE TITLE
Twiss for new SPS symmetric sequence fails

### ISSUE THREAD

**Issue by ewaagaard** [ewaagaard/fma_ions#5]
Cloning the repo and running the test in `tests/sps/test_generating_symmetric_sps_seq.py` fails:
```
Traceback (most recent call last):
  File "/home/elwaagaa/cernbox/PhD/Python/fma_ions/tests/sps/test_generating_symmetric_sps_seq.py", line 7, in <module>
    sps.generate_symmetric_SPS_lattice()
  File "/home/elwaagaa/cernbox/PhD/Projects/fma_ions/fma_ions/sequence_classes_sps.py", line 612, in generate_symmetric_SPS_lattice
    twiss_thin = madx.twiss()  
                 ^^^^^^^^^^^^
  File "/home/elwaagaa/anaconda3/envs/fma_xsuite_env/lib/python3.11/site-packages/cpymad/madx.py", line 388, in twiss
    raise TwissFailed()
cpymad.madx.TwissFailed
```
Loading pre-existing sequence file `SPS_2021_Pb_symmetric.seq` that was generated through this method works - what happened along the way?

**Comment by ewaagaard** [comment]
Also tested to go back to the [commit](https://github.com/ewaagaard/fma_ions/commit/f062c47e29aa793c30ae711b999f91a3c7f8c6e6) where the symmetric case was added - Twiss still fails. Due to different version of cpymad?
